namespace CareerPathRecommender.Web.Infrastructure.Services
{
    using QuestPDF.Fluent;
    using QuestPDF.Helpers;
    using QuestPDF.Infrastructure;
    using CareerPathRecommender.Web.Features.Recommendations;

    public class PdfExportService
    {
        public byte[] GenerateRecommendationsPdf(string employeeName, string targetRole, List<RecommendationDto> recommendations)
        {
            var document = Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Margin(50);
                    page.Size(PageSizes.A4);
                    page.DefaultTextStyle(x => x.FontSize(12));

                    page.Header()
                        .Text($"Career Recommendations for {employeeName}")
                        .FontSize(18).Bold().AlignCenter();

                    page.Content().Column(col =>
                    {
                        col.Spacing(15);

                        col.Item().Text($"Target Role: {targetRole}")
                            .FontSize(14).SemiBold();

                        foreach (var rec in recommendations)
                        {
                            col.Item().Border(1).Padding(10).Column(item =>
                            {
                                item.Item().Text($"Type: {rec.Type}").Bold();
                                item.Item().Text($"Title: {rec.Title}");
                                item.Item().Text($"Reason: {rec.Reason}");
                            });
                        }
                    });

                    page.Footer()
                        .AlignCenter()
                        .Text(x =>
                        {
                            x.Span("Generated by Career Path Recommender");
                            x.Span($"  •  {DateTime.Now:yyyy-MM-dd}");
                        });
                });
            });

            return document.GeneratePdf();
        }
    }

}
